/* Generated By:JavaCC: Do not edit this line. SimpleCConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleCConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETTER = 8;
  /** RegularExpression Id. */
  int DIGIT = 9;
  /** RegularExpression Id. */
  int LPARENT = 10;
  /** RegularExpression Id. */
  int RPARENT = 11;
  /** RegularExpression Id. */
  int LCURLY = 12;
  /** RegularExpression Id. */
  int RCURLY = 13;
  /** RegularExpression Id. */
  int LBRACE = 14;
  /** RegularExpression Id. */
  int RBRACE = 15;
  /** RegularExpression Id. */
  int COMMA = 16;
  /** RegularExpression Id. */
  int SEMICOLON = 17;
  /** RegularExpression Id. */
  int EQUAL = 18;
  /** RegularExpression Id. */
  int AMPERSAND = 19;
  /** RegularExpression Id. */
  int OROR = 20;
  /** RegularExpression Id. */
  int ANDAND = 21;
  /** RegularExpression Id. */
  int EQUALEQUAL = 22;
  /** RegularExpression Id. */
  int NOTEQUAL = 23;
  /** RegularExpression Id. */
  int LESS = 24;
  /** RegularExpression Id. */
  int GREAT = 25;
  /** RegularExpression Id. */
  int LESSEQUAL = 26;
  /** RegularExpression Id. */
  int GREATEQUAL = 27;
  /** RegularExpression Id. */
  int PLUS = 28;
  /** RegularExpression Id. */
  int MINUS = 29;
  /** RegularExpression Id. */
  int TIMES = 30;
  /** RegularExpression Id. */
  int DIVIDE = 31;
  /** RegularExpression Id. */
  int PERCENT = 32;
  /** RegularExpression Id. */
  int CHARSTARSTAR = 33;
  /** RegularExpression Id. */
  int CHARSTAR = 34;
  /** RegularExpression Id. */
  int LONGSTAR = 35;
  /** RegularExpression Id. */
  int LONG = 36;
  /** RegularExpression Id. */
  int VOID = 37;
  /** RegularExpression Id. */
  int IF = 38;
  /** RegularExpression Id. */
  int ELSE = 39;
  /** RegularExpression Id. */
  int WHILE = 40;
  /** RegularExpression Id. */
  int DO = 41;
  /** RegularExpression Id. */
  int FOR = 42;
  /** RegularExpression Id. */
  int CONTINUE = 43;
  /** RegularExpression Id. */
  int BREAK = 44;
  /** RegularExpression Id. */
  int RETURN = 45;
  /** RegularExpression Id. */
  int DOUBLESTAR = 46;
  /** RegularExpression Id. */
  int DOUBLE = 47;
  /** RegularExpression Id. */
  int ID = 48;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\";\"",
    "\"=\"",
    "\"&\"",
    "\"||\"",
    "\"&&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"char**\"",
    "\"char*\"",
    "\"long*\"",
    "\"long\"",
    "\"void\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"for\"",
    "\"continue\"",
    "\"break\"",
    "\"return\"",
    "\"double*\"",
    "\"double\"",
    "<ID>",
  };

}
